NAME: "DifyAgent"
VERSION: "v0.0.1"
# 暴露给前端的参数选项以及默认值
PARAMETERS: [
  {
    NAME: "DIFY_API_URL",
    DEFAULT: "http://dify.zjcst.cn/v1"
  },
  {
    NAME: "DIFY_API_KEY",
    DEFAULT: "app-SfOB3uGvv654R2I4p8ApbgdF"
  },
  {
    NAME: "DIFY_API_USER",
    DEFAULT: "adh"
  }
]